version: '3'

services:
   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - ./wordpress:/var/www/html
     ports:
       - "80:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wp_user_pwd
     networks:
       - app_network
   
   phpymadmin:
     depends_on:
       - db
     image: phpmyadmin/phpmyadmin
     ports:
       - "8080:80"       
     restart: always
     networks:
       - app_network

   db:
     image: mysql:5.7
     volumes:
       - mysql-storage:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wp_user_pwd
     networks:
       - app_network
networks:  
  app_network:

volumes:
  mysql-storage:    
    driver: local

